linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - misspell
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning

run:
  timeout: 5m
  tests: true
